### ISSUE TITLE
表示崩れ問題

### ISSUE THREAD

**Issue by Yokokiri-Cha** [Yokokiri-Cha/CoffeeOSS#2]
一部機種で表示崩れが発生する問題

**Comment by Yokokiri-Cha** [comment]
![image](https://github.com/Yokokiri-Cha/CoffeeOSS/assets/115348123/df245124-2a74-472d-af2f-4c066022cf51)
MiniSearchボタンが押せない例

**Comment by YokochaYokoha** [comment]
CoffeeOSS 5にて解決しました!
